version: '3.9'

services:
  awesome_tracks_api:
    build: ./awesome_tracks_api
    volumes:
      - ./:/usr/local/app
    command:
      - './awesome_tracks_api/bin/server'
    ports:
      - 3000:3000
  weather_service:
    build: ./weather_service
    volumes:
      - ./:/usr/local/app
    environment:
      OPEN_WEATHER_MAP_API_KEY: 'b77e07f479efe92156376a8b07640ced'
    command:
      - './weather_service/bin/server'
  tracks_service:
    build: ./tracks_service
    volumes:
      - ./:/usr/local/app
    environment:
      SPOTIFY_CLIENT_ID: ''
      SPOTIFY_CLIENT_SECRET: ''
    command:
      - './tracks_service/bin/server'
  cache:
    image: redis
