# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tracks_service.proto for package 'tracks_service'

require 'grpc'
require 'tracks_service_pb'

module TracksService
  module Service
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tracks_service.Service'

      rpc :Track, ::TracksService::TrackRequest, ::TracksService::TrackResponse
    end

    Stub = Service.rpc_stub_class
  end
end
